### ISSUE TITLE
Next: add redirects to the YAML files

### ISSUE THREAD

**Issue by bfabio** [italia/designers.italia.it#639] opened 2023-02-21 12:48 UTC
Add all the redirects needed to migrate from the current site to the files in `src/data/content/` by using `redirect_from`.

See #635.

**Comment by Fupete** [comment] 2023-02-21 13:08
FYI @danielaiozzo

**Comment by Fupete** [comment] 2023-03-17 14:02
Update: almost ready by the mighty @gianvitofanelli. Just need a final review and we can merge it.

**Comment by Fupete** [comment] 2023-03-17 15:22
Fixed by merged #666 👹

**Comment by Fupete** [comment] 2023-03-17 16:15
Reopen because part of the issue is still to address: we need to review and add the old redirects already in the current pages. 

Example:

- these redirects from old-current [esperienza utente `yaml`](https://github.com/italia/designers.italia.it/edit/main/_kits/it/esperienza-utente.md)
![old-current](https://user-images.githubusercontent.com/6736103/225959692-b06a948f-dc51-49ef-beb0-27aa45df7c48.png)

- Need to be added to the [new esperienza utente `yaml`](https://github.com/italia/designers.italia.it/blob/next/src/data/content/risorse-per-progettare/comprendere/esperienza-utente.yaml) 
![new-next](https://user-images.githubusercontent.com/6736103/225959830-15680aba-3ca8-4fd4-8bab-89191026d718.png)

**Comment by Fupete** [comment] 2023-03-20 09:46
Closed by #694

**Closed by Fupete** 2023-03-20 09:46 UTC
Labels: content, next
